version: "3"

services:
  client:
    image: gudsson/shopping-cart-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5001
  server:
    image: gudsson/shopping-cart-server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
