export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const INITIALIZE_PRODUCTS = "INITIALIZE_PRODUCTS"

export const INITIALIZE_CARTITEMS = "INITIALIZE_CARTITEMS"
export const ADD_CARTITEM = "ADD_CARTITEM"
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
export const CLEAR_CART = "CLEAR_CART"